// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBks_JTdVPcGMa3l1fWVEcdoyGMzsaAc',
    appId: '1:388190647127:web:b9a5bd3fe284a0b3f78412',
    messagingSenderId: '388190647127',
    projectId: 'ai-justice-7a7a8',
    authDomain: 'ai-justice-7a7a8.firebaseapp.com',
    storageBucket: 'ai-justice-7a7a8.appspot.com',
    measurementId: 'G-0EXCPHNYZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxAoo2NFvhSd3AmxlSKMbsJ3D3zUtiEU',
    appId: '1:388190647127:android:43652ac86990cea1f78412',
    messagingSenderId: '388190647127',
    projectId: 'ai-justice-7a7a8',
    storageBucket: 'ai-justice-7a7a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5q7bJ4SnZhwmvq9uAhDf47cxJmnnuU8',
    appId: '1:388190647127:ios:999a6db365e29989f78412',
    messagingSenderId: '388190647127',
    projectId: 'ai-justice-7a7a8',
    storageBucket: 'ai-justice-7a7a8.appspot.com',
    iosBundleId: 'com.kingrittik.eJusticeV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-5q7bJ4SnZhwmvq9uAhDf47cxJmnnuU8',
    appId: '1:388190647127:ios:999a6db365e29989f78412',
    messagingSenderId: '388190647127',
    projectId: 'ai-justice-7a7a8',
    storageBucket: 'ai-justice-7a7a8.appspot.com',
    iosBundleId: 'com.kingrittik.eJusticeV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBks_JTdVPcGMa3l1fWVEcdoyGMzsaAc',
    appId: '1:388190647127:web:981eb361be0f79f3f78412',
    messagingSenderId: '388190647127',
    projectId: 'ai-justice-7a7a8',
    authDomain: 'ai-justice-7a7a8.firebaseapp.com',
    storageBucket: 'ai-justice-7a7a8.appspot.com',
    measurementId: 'G-1EBJ7WQ5TX',
  );
}
